
spring:
  datasource:
    password: fcpkgn1702051
    url: jdbc:mysql://localhost:3306/webOrnithology
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
