version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 62442
      POSTGRES_DB: db-api-webornithology
    ports:
      - "5432:5432"
    volumes:
      - "/c/Users/DLAR-/data:/var/lib/postgresql/data"