version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTEGRES_USER: postgres
      POSTEGRES_PASSWORD: 62442
      POSTEGRES_DB: db-api-webornithology
    ports:
      - "5432:5432"
    volumes:
      - "./data:var/lib/postegresql/data"